chooseCRANmirror()
install.packages("tseries")
install.packages("timeSeries")
install.packages("stats")
install.packages("forecast")
install.packages("MSBVAR")
install.packages("vars")
install.packages("urca")
install.packages("strucchange")
install.packages("pastecs")
install.packages("deseasonalize")
install.packages("fGarch")
install.packages("tsDyn")
install.packages("apt")
install.packages("doSNOW")

library(tseries)
library(timeSeries)
library(stats)
library(forecast)
library(MSBVAR)
library(vars)
library(urca)
library(strucchange)
library(pastecs)
library(deseasonalize)
library(fGarch)
library(tsDyn)
library(apt)
library(doSNOW)
###########Import Data##################################################
data=read.csv(file="data.csv", header=T)
data=ts(data[,(-1)])
name=colnames(data)
a=data=log(data)